/**
 * N-2 (NFR-2) — with no overlay, `VectorStore.search` is byte-for-byte what it
 * was before phase 5 split it into `buildSearchFilters` → `retrieveCandidates`
 * → `applyOverlay` → `fuseAndHydrate`.
 *
 * `test/testdata/store-search-n2/snapshot.json` was written by
 * `captureSearchSnapshot` against the UNMODIFIED `store.ts` (index blob
 * c83106dd, sha256 30baba77…), before any phase-5 edit. It records, for 12
 * queries over one fixed store, EVERY call the search made on the LanceDB table
 * and its query builders (method + arguments, so every predicate string and
 * every limit) and the full result objects. Deep-equal on both halves: a
 * refactor that changes a predicate, a limit, the call order, an extra read, a
 * score or a hydrated field turns this red.
 *
 * The snapshot is never regenerated by a test. Rewriting it is a deliberate,
 * reviewed act — the point is that it was frozen before the code it judges.
 */

import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import { mkdtempSync, readFileSync, realpathSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
	createVectorStore,
	type IVectorStore,
} from "../../../src/core/store.js";
import {
	captureSearchSnapshot,
	type N2Entry,
	n2Queries,
	normaliseRoot,
	recordTableCalls,
	seedN2Store,
} from "../../helpers/store-search-fixture.js";

const SNAPSHOT = join(
	import.meta.dir,
	"..",
	"..",
	"testdata",
	"store-search-n2",
	"snapshot.json",
);

let dir: string;

async function freshSeededStore(): Promise<IVectorStore> {
	const vectorsDir = join(dir, "vectors");
	const seed = createVectorStore({ vectorsDir, pathRoot: dir });
	await seed.initialize();
	await seedN2Store(seed);
	await seed.close();
	const store = createVectorStore({ vectorsDir, pathRoot: dir });
	await store.initialize();
	return store;
}

beforeAll(() => {
	dir = realpathSync(mkdtempSync(join(tmpdir(), "mnemex-n2-")));
});

afterAll(() => {
	rmSync(dir, { recursive: true, force: true });
});

describe("N-2 — overlay undefined equals the frozen pre-split snapshot", () => {
	test("statements AND results deep-equal, query by query", async () => {
		const frozen = JSON.parse(readFileSync(SNAPSHOT, "utf8")) as N2Entry[];
		expect(frozen.length).toBe(12);
		// Non-vacuous: the snapshot really carries statements and results.
		expect(frozen.every((e) => e.statements.length > 0)).toBe(true);
		expect(frozen.reduce((n, e) => n + e.results.length, 0)).toBeGreaterThan(
			30,
		);

		const store = await freshSeededStore();
		try {
			const now = await captureSearchSnapshot(store, dir);
			expect(now.map((e) => e.name)).toEqual(frozen.map((e) => e.name));
			for (let i = 0; i < frozen.length; i++) {
				expect({ name: now[i].name, statements: now[i].statements }).toEqual({
					name: frozen[i].name,
					statements: frozen[i].statements,
				});
				expect({ name: now[i].name, results: now[i].results }).toEqual({
					name: frozen[i].name,
					results: frozen[i].results,
				});
			}
		} finally {
			await store.close();
		}
	});

	test("an explicit `undefined` fifth argument is the same call", async () => {
		const frozen = JSON.parse(readFileSync(SNAPSHOT, "utf8")) as N2Entry[];
		// A fresh store dir, so the FTS build is in this run's statements too.
		rmSync(join(dir, "vectors"), { recursive: true, force: true });
		const store = await freshSeededStore();
		try {
			const log = await recordTableCalls(store);
			const queries = n2Queries(dir);
			for (let i = 0; i < queries.length; i++) {
				const q = queries[i];
				log.length = 0;
				const search = store.search.bind(store) as (
					...args: unknown[]
				) => ReturnType<IVectorStore["search"]>;
				const results = await search(
					q.query,
					q.vector,
					q.scope,
					q.options,
					undefined,
				);
				expect(normaliseRoot({ statements: [...log], results }, dir)).toEqual({
					statements: frozen[i].statements,
					results: frozen[i].results,
				});
			}
		} finally {
			await store.close();
		}
	});
});
