#!/usr/bin/env bun
// Compare 5 btop-inspired Mode 1 designs side by side
// Each design was independently generated by a different AI model

const R = "\x1b[0m";
const B = "\x1b[1m";
const D = "\x1b[2m"; // dim

// Foreground
const green = (s: string) => `\x1b[32m${s}${R}`;
const bgreen = (s: string) => `\x1b[92m${s}${R}`;
const blue = (s: string) => `\x1b[34m${s}${R}`;
const bblue = (s: string) => `\x1b[94m${s}${R}`;
const cyan = (s: string) => `\x1b[36m${s}${R}`;
const yellow = (s: string) => `\x1b[33m${s}${R}`;
const byellow = (s: string) => `\x1b[93m${s}${R}`;
const red = (s: string) => `\x1b[31m${s}${R}`;
const bred = (s: string) => `\x1b[91m${s}${R}`;
const white = (s: string) => `\x1b[97m${s}${R}`;
const gray = (s: string) => `\x1b[90m${s}${R}`;
const bold = (s: string) => `\x1b[1m${s}${R}`;
const magenta = (s: string) => `\x1b[35m${s}${R}`;
const dim = (s: string) => `\x1b[2m${s}${R}`;

// Background
const bgGreen = (s: string) => `\x1b[42m\x1b[30m${s}${R}`;
const bgBlue = (s: string) => `\x1b[44m\x1b[97m${s}${R}`;
const bgAmber = (s: string) => `\x1b[44m\x1b[97m\x1b[1m${s}${R}`;
const bgGray = (s: string) => `\x1b[48;5;238m\x1b[97m${s}${R}`;

const strip = (s: string) => s.replace(/\x1b\[[0-9;]*m/g, "");
const pad = (s: string, w: number) => {
	const vis = strip(s).length;
	return s + " ".repeat(Math.max(0, w - vis));
};

// Latency coloring
const lat = (ms: number): string => {
	const s = `~${ms}ms`;
	if (ms <= 20) return bgreen(s);
	if (ms <= 100) return byellow(s);
	return bred(s);
};

// Gauge bar: proportional to 500ms max, 14 chars wide
const gauge = (ms: number): string => {
	const maxMs = 500;
	const barW = 14;
	const filled = Math.max(1, Math.round((ms / maxMs) * barW));
	const empty = barW - filled;

	// Pick gauge character based on fill fraction
	const blockChars = "▏▎▍▌▋▊▉█";
	const idx = Math.min(
		Math.floor((ms / maxMs) * (blockChars.length - 1)),
		blockChars.length - 1,
	);
	const ch = blockChars[idx];

	let color: (s: string) => string;
	if (ms <= 20) color = bgreen;
	else if (ms <= 100) color = byellow;
	else color = bred;

	// For small values, just show the fractional block char
	if (filled <= 1) {
		return color(ch) + dim("░".repeat(empty));
	}
	return color("█".repeat(filled - 1) + ch) + dim("░".repeat(empty));
};

// Separator between designs
function separator(title: string, model: string) {
	console.log();
	console.log(bold(`  ${"═".repeat(65)}`));
	console.log(bold(`  DESIGN ${title}`) + `  ${gray(`by ${model}`)}`);
	console.log(bold(`  ${"═".repeat(65)}`));
}

// ═══════════════════════════════════════════════════════════════════
// DESIGN A: Internal (Claude) — Per-step rounded sub-boxes + model wings
// ═══════════════════════════════════════════════════════════════════
function designA() {
	separator("A", "Internal Claude");
	const W = 61;
	const o = (s: string) => {
		console.log(`  │ ${pad(s, W)} │`);
	};

	// Helpers for sub-boxes
	const subTop = (name: string, extra = "") => {
		const label = ` ${name} `;
		const trail = extra ? ` ${extra} ` : "";
		const fill = 42 - label.length - trail.length;
		return bold(`╭─${label}${"─".repeat(Math.max(0, fill))}${trail}╮`);
	};
	const subBot = () => bold("╰" + "─".repeat(42) + "╯");
	const subLine = (content: string) => {
		return bold("│") + `  ${pad(content, 39)}` + bold("│");
	};

	// Model wing box (dim, appears to the right)
	const wingTop = dim("╭────────╮");
	const wingBot = dim("╰────────╯");
	const wingLine = (l1: string, l2: string) =>
		dim("│") + ` ${bgAmber(` ${l1} `)} ` + dim("│");
	const wingAuto = dim("│") + ` ${dim("auto")}   ` + dim("│");

	console.log();
	console.log(
		`  ${bold("MODE 1: LOCAL")}  ${dim("everything on your machine")}`,
	);
	console.log();
	console.log(
		`  ╭─ ${bold(white("mnemex pipeline"))} ${"─".repeat(W - 22)}╮`,
	);
	o("");
	o(dim("source files"));
	o("     │");

	// parse
	o(`${subTop("parse")}           `);
	o(
		`${subLine(`tree-sitter AST          ${bgreen("▏")} ${dim("~5ms  CPU")}`)}           `,
	);
	o(`${subBot()}           `);
	o(`     │ ${dim("text chunks")}`);
	o("     ▼");

	// embed + wing
	o(`${subTop("embed")}  ${wingTop} `);
	o(
		`${subLine(`vectorise chunks         ${byellow("▍")} ${dim("~30ms GPU")}`)}  ${wingLine("embed", "model")} `,
	);
	o(`${subBot()}  ${dim("│")} ${bgAmber(" model ")}  ${dim("│")} `);
	o(`     │ ${dim("vectors")}                   ${dim("◄──────")}${wingAuto} `);
	o(`     ▼                               ${wingBot} `);

	// index
	o(`${subTop("index")}           `);
	o(
		`${subLine(`LanceDB local store      ${bgreen("▏")} ${dim("~5ms  disk")}`)}           `,
	);
	o(`${subBot()}           `);
	o(`     │ ${dim("candidates")}`);
	o("     ▼");

	// search
	o(`${subTop("search")}           `);
	o(
		`${subLine(`vector + BM25 hybrid     ${bgreen("▎")} ${dim("~15ms CPU")}`)}           `,
	);
	o(`${subBot()}           `);
	o(`     │ ${dim("top-K results")}`);
	o("     ▼");

	// rerank + wing
	o(`${subTop("rerank")}  ${wingTop} `);
	o(
		`${subLine(`LLM re-scores results    ${byellow("▌")} ${dim("~100ms GPU")}`)}  ${dim("│")} ${bgAmber(" LLM ")}   ${dim("│")} `,
	);
	o(`${subBot()}  ${dim("│")} ${bgAmber(" model ")}  ${dim("│")} `);
	o(`     │ ${dim("scored results")}            ${dim("◄──────")}${wingAuto} `);
	o(`     ▼                               ${wingBot} `);

	// enrich
	o(`${subTop("enrich", "optional")}          `);
	o(
		`${subLine(`code summaries (same LLM) ${bred("█░")} ${dim("~500ms GPU")}`)}          `,
	);
	o(`${subBot()}           `);
	o(`     │ ${dim("enriched results")}`);
	o("     ▼");
	o(bgreen("results"));
	o("");
	o(`${dim("via Ollama or LM Studio")}    ${bgreen("● zero bytes leave")}`);
	console.log(`  ╰${"─".repeat(W + 2)}╯`);
	console.log();

	// Tech summary
	console.log(dim(`  ${"┄".repeat(59)}`));
	console.log(`  ${bgGray(" Tech Summary ")}  ${bold("Local Mode")}`);
	console.log(
		`  ${green("●")} Runtime     ${white("Ollama or LM Studio (local)")}`,
	);
	console.log(
		`  ${green("●")} Storage     ${white("LanceDB (~50 MB per 10K files)")}`,
	);
	console.log(
		`  ${green("●")} Embedding   ${byellow("auto-detected")} ${dim("e.g. nomic-embed-text 274 MB")}`,
	);
	console.log(
		`  ${green("●")} Rerank      ${byellow("auto-detected")} ${dim("e.g. llama3 8B, 4.7 GB")}`,
	);
	console.log(
		`  ${green("●")} Enrich      ${byellow("same LLM")} ${dim("code summaries, optional")}`,
	);
	console.log(
		`  ${green("●")} Privacy     ${bgreen("air-gapped — zero bytes leave machine")}`,
	);
	console.log(
		`  ${green("●")} Requires    ${white("Apple Silicon or NVIDIA GPU, ≥16 GB RAM")}`,
	);
	console.log();

	// Latency table with gauge bars
	console.log(dim(`  Step     Latency   Gauge          Note`));
	console.log(dim(`  ──────── ───────── ────────────── ────────────────────`));
	console.log(`  parse    ${pad(lat(5), 10)}${gauge(5)}  tree-sitter (CPU)`);
	console.log(`  embed    ${pad(lat(30), 10)}${gauge(30)}  embed model (GPU)`);
	console.log(`  index    ${pad(lat(5), 10)}${gauge(5)}  LanceDB write (disk)`);
	console.log(
		`  search   ${pad(lat(15), 10)}${gauge(15)}  vector + BM25 (CPU)`,
	);
	console.log(
		`  rerank   ${pad(lat(100), 10)}${gauge(100)}  LLM scoring (GPU)`,
	);
	console.log(
		`  enrich   ${pad(lat(500), 10)}${gauge(500)}  LLM summaries (optional)`,
	);
	console.log(dim(`  ─────────────────────────────────────────────────────`));
	console.log(
		`  ${bold("search")}   ${pad(lat(130), 10)}search + rerank (no enrich)`,
	);
	console.log(`  ${bold("full")}     ${pad(lat(630), 10)}all steps end-to-end`);
	console.log(dim(`  approximate — depends on hardware and model size`));
}

// ═══════════════════════════════════════════════════════════════════
// DESIGN B: Minimax — Sub-boxed steps with gauge bars, separate sections
// ═══════════════════════════════════════════════════════════════════
function designB() {
	separator("B", "Minimax M2.5");
	const W = 63;
	const o = (s: string) => console.log(`  │ ${pad(s, W)} │`);
	const top = (title: string) => {
		const label = ` ${title} `;
		const fill = W + 2 - label.length - 2;
		console.log(`  ╭─${label}${"─".repeat(Math.max(0, fill))}╮`);
	};
	const bot = () => console.log(`  ╰${"─".repeat(W + 2)}╯`);

	// Step sub-box
	const stepBox = (name: string, desc: string, ms: number, note: string) => {
		const latStr = lat(ms);
		const barStr = gauge(ms);
		const nameLabel = `[${name}]`;
		o(
			`╭─ ${bold(white(nameLabel))} ${"─".repeat(Math.max(0, 20 - nameLabel.length))}╮  ${pad(latStr, 8)} ${barStr} ${dim(note)}`,
		);
		o(`│ ${desc}`);
		o(`╰${"─".repeat(23)}╯`);
	};

	console.log();
	top("mnemex Mode 1: LOCAL");
	o("");

	top("YOUR MACHINE");
	o("");
	o("  code");
	o(`  │ ${dim("source files")}`);
	o("  ▼");
	stepBox("parse", "text chunks", 5, "(tree-sitter AST)");
	o("  ▼");
	o(
		`  ╭─ ${bold(white("[embed]"))} ${"─".repeat(13)}╮ ${pad(lat(30), 8)} ${gauge(30)} ${dim("(GPU)")}`,
	);
	o(`  │ ◄── ${bgAmber(" embed model ")}`);
	o(`  │ vectors 768-dim`);
	o(`  ╰${"─".repeat(23)}╯`);
	o("  ▼");
	stepBox("index", "candidates", 5, "(LanceDB)");
	o("  ▼");
	stepBox("search", "top-K results", 15, "(vector+BM25)");
	o("  ▼");
	o(
		`  ╭─ ${bold(white("[rerank]"))} ${"─".repeat(12)}╮ ${pad(lat(100), 8)} ${gauge(100)} ${dim("(GPU)")}`,
	);
	o(`  │ ◄── ${bgAmber(" LLM model ")}`);
	o(`  │ scored results`);
	o(`  ╰${"─".repeat(23)}╯`);
	o("  ▼");
	o(
		`  ╭─ ${bold(white("[enrich]"))} ${"─".repeat(12)}╮ ${pad(lat(500), 8)} ${gauge(500)} ${dim("(optional)")}`,
	);
	o(`  │ ◄── ${dim("(same LLM)")}`);
	o(`  │ code summaries`);
	o(`  ╰${"─".repeat(23)}╯`);
	o("  ▼");
	o("  results");
	o("");
	bot();

	console.log();
	top("TECH SUMMARY");
	console.log(
		`  │ ${green("●")} Runtime     ${pad(white("Ollama / LM Studio (local)"), 42)} │`,
	);
	console.log(
		`  │ ${green("●")} Storage     ${pad(white("LanceDB (~50MB per 10K files)"), 42)} │`,
	);
	console.log(
		`  │ ${green("●")} Embed       ${pad(bgAmber(" auto-detected ") + " " + dim("274 MB"), 42)} │`,
	);
	console.log(
		`  │ ${green("●")} Rerank      ${pad(bgAmber(" auto-detected ") + " " + dim("(GPU-based)"), 42)} │`,
	);
	console.log(
		`  │ ${green("●")} Enrich      ${pad(bgAmber(" same LLM ") + " " + dim("(optional)"), 42)} │`,
	);
	console.log(
		`  │ ${green("●")} Privacy     ${pad(bgreen("✓ zero bytes leave machine"), 42)} │`,
	);
	console.log(
		`  │ ${green("●")} Requires    ${pad(white("Apple Silicon or NVIDIA GPU, ≥16 GB RAM"), 42)} │`,
	);
	bot();

	console.log();
	top("LATENCY TABLE");
	console.log(`  │ Step        Time     │ GPU   │ Note${" ".repeat(24)}│`);
	console.log(`  │ ${"─".repeat(20)}┼───────┼${"─".repeat(25)}│`);
	console.log(
		`  │ parse       ${pad(lat(5), 9)}│  -    │ tree-sitter AST (CPU)    │`,
	);
	console.log(
		`  │ embed       ${pad(lat(30), 9)}│ ✓     │ embedding model (GPU)    │`,
	);
	console.log(
		`  │ index       ${pad(lat(5), 9)}│  -    │ LanceDB write (disk)     │`,
	);
	console.log(
		`  │ search      ${pad(lat(15), 9)}│  -    │ vector + BM25 (CPU)      │`,
	);
	console.log(
		`  │ rerank      ${pad(lat(100), 9)}│ ✓     │ LLM scoring (GPU)        │`,
	);
	console.log(
		`  │ enrich      ${pad(lat(500), 9)}│ ✓     │ LLM summaries (GPU)      │`,
	);
	console.log(`  │ ${"─".repeat(20)}┴───────┴${"─".repeat(25)}│`);
	console.log(
		`  │ ${bold("search")}      ${pad(lat(130), 9)}     ${dim("(search + rerank)")}${" ".repeat(13)}│`,
	);
	console.log(
		`  │ ${bold("full")}        ${pad(lat(630), 9)}     ${dim("(all steps end-to-end)")}${" ".repeat(8)}│`,
	);
	console.log(
		`  │ ${" ".repeat(20)}${dim("approximate, depends on hardware")}${" ".repeat(3)}│`,
	);
	bot();
}

// ═══════════════════════════════════════════════════════════════════
// DESIGN C: Kimi — Model gauge panels, privacy banner, bottom title
// ═══════════════════════════════════════════════════════════════════
function designC() {
	separator("C", "Kimi K2.5");
	const W = 47;
	const o = (s: string) => console.log(`  │ ${pad(s, W)} │`);
	const top = (title: string) => {
		const label = ` ${title} `;
		const fill = W + 2 - label.length - 2;
		console.log(`  ╭─${label}${"─".repeat(Math.max(0, fill))}╮`);
	};
	const bot = (title = "") => {
		if (title) {
			const label = ` ${title} `;
			const fill = W + 2 - label.length - 2;
			console.log(`  ╰─${label}${"─".repeat(Math.max(0, fill))}╯`);
		} else {
			console.log(`  ╰${"─".repeat(W + 2)}╯`);
		}
	};

	console.log();
	top("Mode 1: LOCAL");
	console.log(
		`  │ ${pad("everything runs on your machine • air-gapped", W)} │`,
	);
	bot();

	console.log();
	top("Pipeline Flow");
	o("");
	o(dim("source files"));
	o(`   ${cyan("│")}`);
	o(
		`   ${cyan("▼")}  ${bold(green("[parse]"))}  ${dim("tree-sitter")}        ${bgreen("~5ms")}`,
	);
	o(`   ${cyan("│")}  ${dim("AST → text chunks")}`);
	o(`   ${cyan("▼")}`);

	// Embed model gauge panel
	o(`${dim("┌─────────┐")}`);
	o(
		`${dim("│")} ${yellow("▓▓▓▓░░░░░")} ${dim("│")}  ${bold(green("[embed]"))}  ${dim("auto-detected")}   ${byellow("~30ms")}`,
	);
	o(`${dim("│ embed   │")}  ${dim("nomic-embed-text or equiv")}`);
	o(`${dim("│  model  │")}  ${dim("GPU required")}`);
	o(`${dim("└────┬────┘")}`);
	o(`   ${cyan("│")}  ${dim("vectors")}`);
	o(`   ${cyan("▼")}`);
	o(
		`   ${bold(green("[index]"))}  ${dim("LanceDB local storage")}    ${bgreen("~5ms")}`,
	);
	o(`   ${cyan("│")}  ${dim("vector index")}`);
	o(`   ${cyan("▼")}`);
	o(
		`   ${bold(green("[search]"))} ${dim("vector + BM25 hybrid")}   ${bgreen("~15ms")}`,
	);
	o(`   ${cyan("│")}  ${dim("candidates")}`);
	o(`   ${cyan("▼")}`);

	// LLM model gauge panel
	o(`${dim("┌─────────┐")}`);
	o(
		`${dim("│")} ${red("▓▓▓▓▓▓▓▓▓")} ${dim("│")}  ${bold(green("[rerank]"))} ${dim("auto-detected")}  ${byellow("~100ms")}`,
	);
	o(`${dim("│   LLM   │")}  ${dim("llama3/codellama or equiv")}`);
	o(`${dim("│  model  │")}  ${dim("GPU required")}`);
	o(`${dim("└────┬────┘")}`);
	o(`   ${cyan("│")}  ${dim("scored results")}`);
	o(`   ${cyan("▼")}`);
	o(
		`   ${bold(green("[enrich]"))} ${dim("code summaries")}        ${bred("~500ms")}`,
	);
	o(`   ${cyan("│")}  ${dim("optional step")}        ${dim("(same LLM)")}`);
	o(`   ${cyan("▼")}`);
	o(`${bgreen("▓▓▓ RESULTS ▓▓▓")}`);
	o("");
	bot("Ollama / LM Studio");

	console.log();
	top("Tech Specs");
	o("");
	o(`${green("●")} Runtime    ${white("Ollama or LM Studio")}`);
	o(`${green("●")} Storage    ${white("LanceDB ~50MB per 10K files")}`);
	o(
		`${green("●")} Embedding  ${byellow("auto-detected")} ${dim("137-274 MB")}`,
	);
	o(
		`${green("●")} LLM        ${byellow("auto-detected")} ${dim("4-8 GB VRAM")}`,
	);
	o(`${green("●")} Enrich     ${byellow("same LLM")} ${dim("optional step")}`);
	o(`${green("●")} Privacy    ${bgreen("█ ZERO BYTES LEAVE MACHINE █")}`);
	o(`${green("●")} Requires   ${white("Apple Silicon or NVIDIA")}`);
	o(`           ${white("≥16 GB RAM, ~5 GB VRAM free")}`);
	o("");
	bot();

	console.log();
	top("Latency Breakdown");
	o("");
	o(`Step        Latency    Visual`);
	o(`${"─".repeat(41)}`);
	o(`parse       ${pad(bgreen("~5ms"), 11)}  ${bgreen("▏")}`);
	o(`embed       ${pad(byellow("~30ms"), 11)}  ${yellow("▋")}`);
	o(`index       ${pad(bgreen("~5ms"), 11)}  ${bgreen("▏")}`);
	o(`search      ${pad(bgreen("~15ms"), 11)}  ${bgreen("▎")}`);
	o(`rerank      ${pad(byellow("~100ms"), 11)}  ${yellow("▊")}`);
	o(`enrich      ${pad(bred("~500ms"), 11)}  ${red("████")}`);
	o(`${"─".repeat(41)}`);
	o(
		`${bold("search")}      ${pad(byellow("~130ms"), 11)}  ${yellow("█▎")}   ${dim("(no enrich)")}`,
	);
	o(
		`${bold("full")}        ${pad(bred("~630ms"), 11)}  ${red("█████▎")} ${dim("(with enrich)")}`,
	);
	o("");
	bot(dim("approximate, depends on hardware"));
}

// ═══════════════════════════════════════════════════════════════════
// DESIGN D: GLM — Horizontal card layout, steps side-by-side
// ═══════════════════════════════════════════════════════════════════
function designD() {
	separator("D", "GLM-5");
	const W = 70;

	console.log();
	console.log(
		`  ${bold(white(`╭${"─".repeat(W - 2)} MODE 1: LOCAL ${"─".repeat(3)}╮`))}`,
	);
	console.log(`  │${" ".repeat(W + 2)}│`);

	// Horizontal pipeline flow
	console.log(
		`  │  ${dim("code ──► parse ──► embed ──► index ──► search ──► rerank ──► enrich")} │`,
	);
	console.log(`  │${" ".repeat(W + 2)}│`);

	// Cards row - parse and embed
	console.log(
		`  │  ┌──────────────┐ ┌───────────────┐ ┌────────────┐ ┌──────────────┐ │`,
	);
	console.log(
		`  │  │   PARSE      │ │    EMBED      │ │   SEARCH   │ │   RERANK     │ │`,
	);
	console.log(
		`  │  │ ${cyan("tree-sitter")}  │ │ ${yellow("◄ embed model")} │ │ ${cyan("vector+BM25")} │ │ ${yellow("◄ LLM model")}  │ │`,
	);
	console.log(
		`  │  │ ${dim("AST → chunks")} │ │ ${dim("chunks → vecs")}  │ │ ${dim("top-K result")}│ │ ${dim("LLM rescores")} │ │`,
	);
	console.log(
		`  │  │  ${bgreen("~5ms")}       │ │  ${byellow("~30ms")}        │ │  ${bgreen("~15ms")}    │ │  ${byellow("~100ms")}      │ │`,
	);
	console.log(
		`  │  └──────────────┘ └───────────────┘ └────────────┘ └──────────────┘ │`,
	);
	console.log(`  │${" ".repeat(W + 2)}│`);

	// Enrich + Index
	console.log(
		`  │             ┌───────────────────────────────────────┐                │`,
	);
	console.log(
		`  │             │           ENRICH (optional)           │                │`,
	);
	console.log(
		`  │             │       ${dim("(same LLM, code summaries)")}        │                │`,
	);
	console.log(
		`  │             │                       ${bred("~500ms")}          │                │`,
	);
	console.log(
		`  │             └───────────────────────────────────────┘                │`,
	);
	console.log(`  │${" ".repeat(W + 2)}│`);
	console.log(
		`  │                    ┌────────────────────────────┐                    │`,
	);
	console.log(
		`  │                    │         INDEX STORE        │                    │`,
	);
	console.log(
		`  │                    │      ${cyan("LanceDB (local)")}         │                    │`,
	);
	console.log(
		`  │                    │         ${bgreen("~5ms")}               │                    │`,
	);
	console.log(
		`  │                    └────────────────────────────┘                    │`,
	);
	console.log(`  │${" ".repeat(W + 2)}│`);
	console.log(
		`  │                    ▼                                                 │`,
	);
	console.log(
		`  │               ${bgreen(bold("RESULTS"))}                                             │`,
	);
	console.log(`  │${" ".repeat(W + 2)}│`);
	console.log(`  ├${"─".repeat(W + 2)}┤`);

	// Info section
	console.log(
		`  │  ${green("●")} Runtime  ${white("Ollama / LM Studio")}${" ".repeat(34)}│`,
	);
	console.log(
		`  │  ${green("●")} Privacy  ${bgreen(bold("AIR-GAPPED"))} ${dim("zero bytes leave machine")}${" ".repeat(12)}│`,
	);
	console.log(
		`  │  ${green("●")} Requires ${white("Apple Silicon / NVIDIA GPU")}${" ".repeat(27)}│`,
	);
	console.log(
		`  │  ${green("●")} Memory   ${byellow("≥16 GB RAM")}${" ".repeat(43)}│`,
	);
	console.log(`  ├${"─".repeat(W + 2)}┤`);
	console.log(`  │${" ".repeat(W + 2)}│`);
	console.log(`  │  ${dim("LATENCY TABLE")}${" ".repeat(W + 2 - 15)}│`);
	console.log(`  │  ${dim("─".repeat(48))}${" ".repeat(W + 2 - 50)}│`);

	// Latency bars
	const latBar = (name: string, ms: number, note: string) => {
		const barW = 20;
		const filled = Math.max(1, Math.round((ms / 500) * barW));
		const empty = barW - filled;
		let color: (s: string) => string;
		if (ms <= 20) color = bgreen;
		else if (ms <= 100) color = byellow;
		else color = bred;
		const bar = color("█".repeat(filled)) + dim("░".repeat(empty));
		const latStr =
			ms <= 20
				? bgreen(`~${ms}ms`)
				: ms <= 100
					? byellow(`~${ms}ms`)
					: bred(`~${ms}ms`);
		const line = `  ${pad(name, 8)} ${bar}  ${pad(latStr, 8)} ${dim(note)}`;
		console.log(`  │${pad(line, W + 2)}│`);
	};

	latBar("parse", 5, "CPU");
	latBar("embed", 30, "GPU required");
	latBar("index", 5, "disk write");
	latBar("search", 15, "CPU");
	latBar("rerank", 100, "GPU required");
	latBar("enrich", 500, "GPU, optional");
	console.log(`  │  ${dim("─".repeat(48))}${" ".repeat(W + 2 - 50)}│`);
	console.log(
		`  │  ${bold("search total")}              ${byellow("~130ms")} ${dim("(no enrich)")}${" ".repeat(20)}│`,
	);
	console.log(
		`  │  ${bold("full pipeline")}             ${bred("~630ms")} ${dim("(with enrich)")}${" ".repeat(18)}│`,
	);
	console.log(`  │${" ".repeat(W + 2)}│`);
	console.log(`  ╰${"─".repeat(W + 2)}╯`);
}

// ═══════════════════════════════════════════════════════════════════
// DESIGN E: Gemini — Most compact, unified dashboard
// ═══════════════════════════════════════════════════════════════════
function designE() {
	separator("E", "Gemini 3.1 Pro");
	const W = 63;

	console.log();
	console.log(`  ╭─ MODE 1: LOCAL FULL ${"─".repeat(W - 22)}╮`);

	// Top info bar
	console.log(
		`  │ ${green("●")} Privacy : 0 bytes external   ${green("●")} Platform: Ollama / LM Studio │`,
	);
	console.log(
		`  │ ${green("●")} Hardware: Apple Silic/NVIDIA ${green("●")} Memory  : ≥16 GB RAM         │`,
	);

	// Pipeline section
	console.log(`  ├─ PIPELINE & LATENCY ${"─".repeat(W - 23)}┤`);

	// Compact pipeline boxes
	console.log(
		`  │ ╭─────╮ ╭─────╮ ╭─────╮ ╭──────╮ ╭──────╮ ╭──────╮            │`,
	);
	console.log(
		`  │ │parse│▶│embed│▶│index│▶│search│▶│rerank│▶│enrich│▶ ${dim("results")}   │`,
	);
	console.log(
		`  │ ╰─────╯ ╰─────╯ ╰─────╯ ╰──────╯ ╰──────╯ ╰──────╯            │`,
	);
	console.log(
		`  │  ${cyan("CPU")}     ${magenta("GPU")}     ${blue("DSK")}     ${cyan("CPU")}      ${magenta("GPU")}      ${magenta("GPU")}               │`,
	);
	console.log(
		`  │  ${dim("5ms")}     ${dim("30ms")}    ${dim("5ms")}     ${dim("15ms")}     ${dim("100ms")}    ${dim("500ms")}             │`,
	);

	// Mini gauge blocks (proportional)
	console.log(
		`  │  ${cyan("▏")}       ${magenta("▎")}       ${blue("▏")}       ${cyan("▏")}        ${magenta("▊")}        ${magenta("█")}                │`,
	);

	// Resources section
	console.log(`  ├─ ENGINES & RESOURCES ${"─".repeat(W - 24)}┤`);

	// Resource utilization bars
	const resBar = (
		name: string,
		model: string,
		type: string,
		typeColor: (s: string) => string,
		filled: number,
		total: number,
	) => {
		const bar = "▊".repeat(filled) + "░".repeat(total - filled);
		console.log(
			`  │ ${dim(pad(name, 10))} [ ${pad(white(model), 17)} ] ${typeColor(type)} ${bar} ${bgreen("OK")}      │`,
		);
	};

	resBar("Embed Slot", "Auto-detecting...", "GPU", magenta, 5, 15);
	resBar("LLM Slot  ", "Auto-detecting...", "GPU", magenta, 11, 15);
	resBar("Vector DB ", "LanceDB Local    ", "DSK", blue, 2, 15);

	console.log(`  ╰${"─".repeat(W + 2)}╯`);
}

// ═══════════════════════════════════════════════════════════════════
// MAIN
// ═══════════════════════════════════════════════════════════════════
console.log();
console.log(
	bold(
		"  ╔══════════════════════════════════════════════════════════════════╗",
	),
);
console.log(
	bold("  ║     BTOP-INSPIRED MODE 1 DESIGNS — SIDE-BY-SIDE COMPARISON      ║"),
);
console.log(
	bold(
		"  ╚══════════════════════════════════════════════════════════════════╝",
	),
);
console.log(
	dim("  5 independent designs from 5 AI models, each inspired by btop"),
);

designA(); // Internal Claude
designB(); // Minimax M2.5
designC(); // Kimi K2.5
designD(); // GLM-5
designE(); // Gemini 3.1 Pro

console.log();
console.log(
	bold("  ═══════════════════════════════════════════════════════════════════"),
);
console.log(`  ${dim("Run:")} bun run src/tui/setup/btop-designs-compare.ts`);
console.log(
	`  ${dim("Pick your favourite and we'll integrate it into the wizard")}`,
);
console.log();
