/**
 * Markdown Format
 *
 * Produces a Markdown document with:
 * - H1 title
 * - H2 directory structure section (fenced code block)
 * - H3 per-file sections with fenced code blocks + language detection
 */

import type { FileEntry, PackMeta } from "../types.js";

// ============================================================================
// Functions
// ============================================================================

/**
 * Format pack output as Markdown.
 *
 * Structure:
 * ```markdown
 * # Codebase: {name}
 *
 * Generated by mnemex pack on {date}. Files: {N}. Tokens (est.): {N}.
 *
 * ## Directory Structure
 *
 * ```
 * {tree}
 * ```
 *
 * ### File: src/cli.ts
 *
 * ```typescript
 * {content}
 * ```
 * ```
 *
 * @param entries - File entries to include
 * @param tree - Pre-built directory tree string
 * @param meta - Pack metadata
 * @returns Formatted Markdown string
 */
export function formatMarkdown(
	entries: FileEntry[],
	tree: string,
	meta: PackMeta,
): string {
	const textFiles = entries.filter((e) => !e.isBinary);
	const parts: string[] = [];

	// H1 title
	parts.push(`# Codebase: ${meta.projectName}`);
	parts.push("");
	parts.push(
		`Generated by mnemex pack on ${meta.generatedAt}. Files: ${meta.fileCount}. Tokens (est.): ${meta.estimatedTokens}.`,
	);
	parts.push("");

	// Directory structure
	parts.push("## Directory Structure");
	parts.push("");
	parts.push("```");
	parts.push(tree);
	parts.push("```");
	parts.push("");

	// Per-file sections
	for (const entry of textFiles) {
		parts.push(`### File: ${entry.relativePath}`);
		parts.push("");

		const lang = entry.language ?? "";
		const content = entry.content ?? "";

		// Use a fence longer than any backtick sequence in the content
		// to avoid breaking the code fence structure
		const backtickRuns = content.match(/`{3,}/g) ?? [];
		const maxBackticks = Math.max(3, ...backtickRuns.map((m) => m.length));
		const fence = "`".repeat(maxBackticks + 1);

		parts.push(`${fence}${lang}`);
		parts.push(content);
		parts.push(fence);
		parts.push("");
	}

	return parts.join("\n");
}
