/**
 * XML Format
 *
 * Produces repomix-compatible XML output.
 * Each file is wrapped in <file path="..."> tags.
 */

import type { FileEntry, PackMeta } from "../types.js";

// ============================================================================
// Functions
// ============================================================================

/**
 * Escape XML special characters in content.
 * Avoids breaking the XML structure when file content contains <, >, &, etc.
 */
function escapeXml(text: string): string {
	return text
		.replace(/&/g, "&amp;")
		.replace(/</g, "&lt;")
		.replace(/>/g, "&gt;");
}

/**
 * Format pack output as repomix-compatible XML.
 *
 * Structure:
 * ```
 * This file is a merged representation of the entire codebase...
 *
 * <file_summary>...</file_summary>
 *
 * <directory_structure>
 * {tree}
 * </directory_structure>
 *
 * <files>
 * <file path="...">
 * {content}
 * </file>
 * </files>
 * ```
 *
 * @param entries - File entries to include
 * @param tree - Pre-built directory tree string
 * @param meta - Pack metadata
 * @returns Formatted XML string
 */
export function formatXml(
	entries: FileEntry[],
	tree: string,
	meta: PackMeta,
): string {
	const textFiles = entries.filter((e) => !e.isBinary);
	const parts: string[] = [];

	// Preamble (repomix-compatible)
	parts.push(
		"This file is a merged representation of the entire codebase, combined into a single document by claudemem pack.",
	);
	parts.push("");

	// File summary
	parts.push("<file_summary>");
	parts.push(
		"  <purpose>This file contains a packed representation of the codebase for AI analysis.</purpose>",
	);
	parts.push(
		"  <file_format>Each file is wrapped in file tags with path attribute.</file_format>",
	);
	parts.push(
		"  <usage_guidelines>Use this for code review, analysis, or understanding the codebase.</usage_guidelines>",
	);
	parts.push(
		`  <notes>Generated by claudemem pack. Files: ${meta.fileCount}. Tokens (est.): ${meta.estimatedTokens}.</notes>`,
	);
	parts.push("</file_summary>");
	parts.push("");

	// Directory structure
	parts.push("<directory_structure>");
	parts.push(tree);
	parts.push("</directory_structure>");
	parts.push("");

	// Files
	parts.push("<files>");
	for (const entry of textFiles) {
		parts.push(`<file path="${escapeXml(entry.relativePath)}">`);
		parts.push(escapeXml(entry.content ?? ""));
		parts.push("</file>");
	}
	parts.push("</files>");

	return parts.join("\n");
}
